//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biens
    {
        public int BienID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public int HeritageID { get; set; }
    
        public virtual Heritage Heritage { get; set; }
    }
}
