//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heritier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Heritier()
        {
            this.AyantDroit = new HashSet<AyantDroit>();
        }
    
        public int NomenclatureID { get; set; }
        public string Sexe { get; set; }
        public string Description { get; set; }
        public int HeritageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AyantDroit> AyantDroit { get; set; }
        public virtual Heritage Heritage { get; set; }
    }
}
