//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heritage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Heritage()
        {
            this.Biens = new HashSet<Biens>();
            this.Heritier = new HashSet<Heritier>();
        }
    
        public int HeritageID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateDece { get; set; }
        public Nullable<System.DateTime> DateHeritage { get; set; }
        public int EcoleID { get; set; }
        public decimal Montant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biens> Biens { get; set; }
        public virtual Ecole Ecole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Heritier> Heritier { get; set; }
    }
}
