//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCSharp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdHeritagesEntities : DbContext
    {
        public BdHeritagesEntities()
            : base("name=BdHeritagesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AyantDroit> AyantDroit { get; set; }
        public virtual DbSet<Biens> Biens { get; set; }
        public virtual DbSet<Ecole> Ecole { get; set; }
        public virtual DbSet<Heritage> Heritage { get; set; }
        public virtual DbSet<Heritier> Heritier { get; set; }
        public virtual DbSet<Regles> Regles { get; set; }
        public virtual DbSet<Sources> Sources { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
